import {createRequire} from 'node:module';import fs from 'node:fs';
const require=createRequire('/Users/jyxc-dz-0100378/TESTBMK/game-skill-packages/verification/allgame/racing-custom/package.json');const{chromium}=require('playwright');const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-angle=metal']});
const out='/tmp/creative-game-authoring/gallery';fs.mkdirSync(out,{recursive:true});let report=[];
for(const id of ['survivorgame','towerdefensegame','platformgame','farmgame']){
 const page=await browser.newPage({viewport:{width:1600,height:1000},deviceScaleFactor:1});let errors=[];page.on('pageerror',e=>errors.push(String(e)));
 await page.goto('http://127.0.0.1:4491/'+id+'/?dev=1');await page.waitForSelector('[data-do=start]');await page.waitForTimeout(250);await page.screenshot({path:`${out}/${id}-menu.png`});await page.locator('[data-theme]').last().click();await page.waitForTimeout(100);await page.screenshot({path:`${out}/${id}-alt-menu.png`});await page.locator('[data-theme]').first().click();await page.click('[data-do=start]');await page.click('#sound');
 if(id==='towerdefensegame')await page.evaluate(()=>{let d=__GAME__,g=d.game;const order=[1,4,6,2,0,3,5,7];let pos=0;for(let i=0;i<22000&&d.stage==='playing'&&g.wave<4;i++){if(pos<order.length){let idx=order[pos];g.action(pos===3?'frost':pos===5?'flame':'arrow');let cost=g.selected==='frost'?80:g.selected==='flame'?110:65;if(g.gold>=cost){g.click(g.pads[idx].x,g.pads[idx].y);pos++;}}else{let q=g.towers.find(t=>t.level<3&&g.gold>=45*t.level);if(q){g.selectedPad=q.pad;g.action('upgrade');}}if(!g.active)g.action('wave');g.update(1/60);}d.step(9);});
 if(id==='farmgame')await page.evaluate(()=>{let g=__GAME__.game;const point=q=>[650+(q.col-q.row)*65,378+(q.col+q.row)*32];for(let cycle=0;cycle<2;cycle++){for(let q of g.plots){let [x,y]=point(q);if(!q.crop&&g.gold>=3){if(g.energy<2)g.action('sleep');g.action('carrot');g.click(x,y);}if(q.crop&&!q.water){if(!g.energy)g.action('sleep');g.action('water');g.click(x,y);}}for(let q of g.plots.filter(q=>q.crop)){if(!q.water){if(!g.energy)g.action('sleep');g.action('water');g.click(...point(q));}for(let t=0;t<45;t++)g.update(1);g.click(...point(q));}g.action('sell');}g.action('build');g.action('build');for(let q of g.plots){if(g.energy<2)g.action('sleep');g.action(['carrot','berry','flower'][(q.col+q.row)%3]);g.click(...point(q));g.action('water');g.click(...point(q));for(let t=0;t<50;t++)g.update(1);}});
 if(id==='survivorgame')for(let batch=0;batch<400;batch++){let s=await page.evaluate(()=>{let d=__GAME__,g=d.game;for(let i=0;i<24&&d.stage==='playing';i++){let p=g.player,a=g.time*.3,dx=640+Math.cos(a)*240-p.x,dy=490+Math.sin(a)*150-p.y;let gem=g.gems.find(q=>Math.hypot(q.x-p.x,q.y-p.y)<200);if(gem){dx=gem.x-p.x;dy=gem.y-p.y;}for(let e of g.enemies){let ex=p.x-e.x,ey=p.y-e.y,r=Math.hypot(ex,ey);if(r<125){dx+=ex/Math.max(1,r)*(125-r)*3;dy+=ey/Math.max(1,r)*(125-r)*3;}}let l=Math.hypot(dx,dy)||1;d.input.x=dx/l;d.input.y=dy/l;g.update(1/60,d.input);}return{stage:d.stage,time:g.time};});if(s.stage==='choice')await page.locator('[data-choice]').first().click();if(s.time>92||s.stage==='result')break;}
 if(id==='platformgame'){
  const script=fs.readFileSync('/tmp/creative-game-authoring/test-browser.mjs','utf8');let start=script.indexOf('result.playthrough=await page.evaluate(()=>{let d=__GAME__,g=d.game,frames=0');let end=script.indexOf(');assert(result.playthrough.stage',start);let fn=script.slice(start+'result.playthrough=await page.evaluate('.length,end).replace('frames<30000','frames<550');await page.evaluate(eval('('+fn+')'));
 }
 await page.waitForTimeout(2600);await page.screenshot({path:`${out}/${id}-play.png`});report.push({id,errors,stage:await page.evaluate(()=>__GAME__.stage)});await page.close();
}
// Desktop no-debug launch and actual mobile touch, independent of game-state injection.
for(const id of ['survivorgame','towerdefensegame','platformgame','farmgame']){
 let page=await browser.newPage({viewport:{width:844,height:528},isMobile:true,hasTouch:true});let errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto('http://127.0.0.1:4491/'+id+'/');await page.waitForSelector('[data-do=start]');await page.touchscreen.tap(...await page.locator('[data-do=start]').evaluate(e=>{let r=e.getBoundingClientRect();return[r.x+r.width/2,r.y+r.height/2];}));await page.waitForTimeout(150);
 if(id==='survivorgame'||id==='platformgame'){const s=await page.locator('#stick').boundingBox();const cdp=await page.context().newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:s.x+s.width*.8,y:s.y+s.height*.5}]});await page.waitForTimeout(450);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.touchscreen.tap(...await page.locator('#touch-action').evaluate(e=>{let r=e.getBoundingClientRect();return[r.x+r.width/2,r.y+r.height/2];}));}
 else{const canvas=await page.locator('canvas').boundingBox();const[x,y]=id==='farmgame'?[845,474]:[352,484];await page.touchscreen.tap(canvas.x+x/1280*canvas.width,canvas.y+y/800*canvas.height);}
 await page.waitForTimeout(250);await page.screenshot({path:`${out}/${id}-touch.png`});report.push({id,mode:'mobile-landscape',errors,debugExposed:await page.evaluate(()=>typeof window.__GAME__!=='undefined'),menuClosed:await page.locator('#overlay').evaluate(e=>!e.children.length)});await page.close();
}
fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));console.log(report);await browser.close();
