export class Input{
 constructor(canvas,onAction,onOrbit,onZoom){this.keys=new Set();this.move={x:0,z:0};this.drag=null;this.moved=0;
 const keyActions={KeyE:'capture',KeyQ:'twine',KeyC:'scan',KeyM:'map',KeyB:'dex',KeyP:'photo',Escape:'escape',Space:'jump',Digit1:'select0',Digit2:'select1',Digit3:'select2',Digit4:'select3'};
 window.addEventListener('keydown',e=>{if(['Space','Tab','ArrowUp','ArrowDown'].includes(e.code))e.preventDefault();if(e.repeat)return;this.keys.add(e.code);if(keyActions[e.code])onAction(keyActions[e.code]);});window.addEventListener('keyup',e=>this.keys.delete(e.code));window.addEventListener('blur',()=>this.release());document.addEventListener('visibilitychange',()=>{if(document.hidden)this.release();});
 canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerdown',e=>{this.drag={id:e.pointerId,x:e.clientX,y:e.clientY,button:e.button};this.moved=0;canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!this.drag||this.drag.id!==e.pointerId)return;const dx=e.clientX-this.drag.x,dy=e.clientY-this.drag.y;this.moved+=Math.abs(dx)+Math.abs(dy);onOrbit(-dx*.004,-dy*.003);this.drag.x=e.clientX;this.drag.y=e.clientY;});canvas.addEventListener('pointerup',e=>{if(this.drag&&this.moved<5&&this.drag.button===0&&e.pointerType!=='touch')onAction('capture');this.drag=null;});canvas.addEventListener('pointercancel',()=>this.release());canvas.addEventListener('wheel',e=>{e.preventDefault();onZoom(e.deltaY*.007);},{passive:false});
 }
 joystick(){const el=document.querySelector('#joystick');if(!el)return;const stick=el.querySelector('i');let active=null;const set=e=>{const r=el.getBoundingClientRect();let x=(e.clientX-r.x-r.width/2)/34,z=(e.clientY-r.y-r.height/2)/34;const len=Math.hypot(x,z);if(len>1){x/=len;z/=len;}this.move={x,z};stick.style.transform=`translate(${x*26}px,${z*26}px)`;};el.addEventListener('pointerdown',e=>{active=e.pointerId;el.setPointerCapture(e.pointerId);set(e);});el.addEventListener('pointermove',e=>{if(e.pointerId===active)set(e);});for(const type of ['pointerup','pointercancel','lostpointercapture'])el.addEventListener(type,()=>{active=null;this.move={x:0,z:0};stick.style.transform='';});}
 axes(){let x=(this.keys.has('KeyD')?1:0)-(this.keys.has('KeyA')?1:0)+this.move.x,z=(this.keys.has('KeyS')?1:0)-(this.keys.has('KeyW')?1:0)+this.move.z;const d=Math.hypot(x,z);if(d>1){x/=d;z/=d;}return{x,z,sprint:this.keys.has('ShiftLeft')||this.keys.has('ShiftRight')};}
 release(){this.keys.clear();this.move={x:0,z:0};this.drag=null;const s=document.querySelector('#joystick>i');if(s)s.style.transform='';}
}
