import {SPECIES,WILD,PORTAL,uniqueSpecies} from './state.js';
import {riverX,heightAt} from './terrain.js';
const paths={map:'<path d="m3 5 6-2 6 2 6-2v16l-6 2-6-2-6 2V5Zm6-2v16m6-14v16"/>',paw:'<ellipse cx="12" cy="15.5" rx="5.7" ry="4.5"/><ellipse cx="5" cy="8" rx="2" ry="3"/><ellipse cx="10" cy="5" rx="2" ry="3"/><ellipse cx="16" cy="5" rx="2" ry="3"/><ellipse cx="20" cy="10" rx="2" ry="3"/>',link:'<path d="m9 15 6-6m-5-4 2-2a5 5 0 0 1 7 7l-3 3m-2 6-2 2a5 5 0 0 1-7-7l3-3"/>',camera:'<path d="M3 7h4l2-3h6l2 3h4v13H3V7Z"/><circle cx="12" cy="13" r="4"/>',settings:'<path d="m9 3-.7 3-3 1L3 10l2 3v4l4 1 3 3 3-3 4-1v-4l2-3-2.3-3-3-1L15 3H9Z"/><circle cx="12" cy="12" r="3"/>',compass:'<circle cx="12" cy="12" r="9"/><path d="m15.5 8.5-2 5-5 2 2-5 5-2Z"/>',orb:'<circle cx="12" cy="12" r="9"/><path d="M3 11h6m6 0h6"/><circle cx="12" cy="11" r="3"/><path d="m8 5-2 2"/>',leaf:'<path d="M20 3C8 2 1 10 6 17c7 5 15-2 14-14ZM4 21 16 9"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 1v3m0 16v3M1 12h3m16 0h3M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2"/>',arrow:'<path d="m5 12 14 0m-6-6 6 6-6 6"/>',close:'<path d="m5 5 14 14M5 19 19 5"/>',sound:'<path d="m11 4-6 5H2v6h3l6 5V4Zm4 3a7 7 0 0 1 0 10m3-13a11 11 0 0 1 0 16"/>',reset:'<path d="M3 11a9 9 0 1 1 2 7M3 4v7h7"/>',flag:'<path d="M5 22V3m0 1c5-4 8 4 14 0v10c-6 4-9-4-14 0"/>',spark:'<path d="m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3 3-7Z"/>',jump:'<path d="m5 13 7-7 7 7M12 6v15M6 2h12"/>'};
export function icon(name){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||paths.spark}</svg>`;}
export class UI{
 constructor(state,portraits,actions){this.state=state;this.portraits=portraits;this.actions=actions;this.modal=null;this.photo=false;this.lastMap=0;this.dexIndex=0;this.root=document.querySelector('#ui');this.root.innerHTML=`
 <div class="hud">
 <div class="map-cluster"><button class="minimap-button" data-action="map" aria-label="打开世界地图 M"><canvas id="minimap" width="310" height="310"></canvas><span class="north">N</span><span class="map-key">M</span></button><div class="map-caption">${icon('sun')}<span>晴 · 微风</span><span class="world-time">09:41</span></div></div>
 <div class="location"><span class="location-top">A E D E L &nbsp; / &nbsp; 艾德尔大陆</span><h1>风栖原野<span>✦</span></h1><p>每一次相遇，都是新的开始</p></div>
 <div class="top-right"><div class="wordmark">伊莫<small>ANIIMO</small></div><div class="top-tools">${[['paw','dex','伊莫图鉴','B'],['map','map','世界地图','M'],['camera','photo','摄影模式','P'],['settings','pause','设置','Esc']].map(([i,a,l,k])=>`<button data-action="${a}" class="tool" title="${l} ${k}" aria-label="${l}">${icon(i)}<small>${k}</small></button>`).join('')}</div></div>
 <button class="quest" data-action="quest"><span class="quest-star">${icon('spark')}</span><span><small>原野初遇 · 探索委托</small><strong id="quest-title">与原野的伊莫成为伙伴</strong><span class="quest-line"><i></i><span id="quest-detail">结识 3 种不同的伊莫</span><b id="quest-count">0 / 3</b></span><em id="quest-hint">沿着花香，寻找新的相遇</em></span><span class="quest-expand">›</span></button>
 <div class="explore-tag"><span class="live-dot"></span>自由探索<span> / </span><b id="discover">0</b><small>种相遇</small></div>
 <div class="party"><div class="party-title">我的伙伴</div>${SPECIES.map((s,i)=>`<button class="partner locked" data-species="${i}" style="--pet-color:${s.color}" aria-label="切换伙伴 ${s.name}"><img src="${portraits[i]}" alt="${s.name}"/><span class="partner-number">${i+1}</span><span class="partner-name">${s.name}</span><span class="lock-dot">+</span></button>`).join('')}<button class="party-more" data-action="dex" aria-label="查看图鉴">···</button></div>
 <div id="target-label" class="target-label" hidden><div><small>Lv. 02</small><b id="target-name">绵云</b><span id="target-element">风</span></div><span class="target-line"></span><small class="target-mood">可以靠近 · 性情温和</small></div>
 <div class="center-reticle"><i></i></div><div id="waypoint" class="waypoint" hidden>${icon('spark')}<span>风之门</span><b>0m</b></div>
 <div class="player-bar"><div class="player-emblem">${icon('compass')}<span>01</span></div><div><div class="player-name"><b id="player-name">原野旅人</b><span id="player-form">探索者</span></div><div class="health"><i></i></div><div class="player-sub"><span>风栖原野的第一天</span><span id="steps">0 m</span></div></div></div>
 <div class="bottom-center"><div id="twine-status">${icon('link')} <span>与伊莫联结，发现另一种可能</span></div><div class="movement-hints"><kbd>W</kbd><span class="asd"><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd></span><span>移动</span><i></i><kbd>Shift</kbd><span>疾跑</span><kbd>Space</kbd><span>跳跃</span><span class="mouse-icon"></span><span>拖动视角</span></div></div>
 <div class="skills"><button class="skill small" data-action="scan" aria-label="寻找伊莫 C">${icon('compass')}<kbd>C</kbd><span>感知</span></button><button class="skill small" data-action="twine" id="twine-button" aria-label="联结合体 Q">${icon('link')}<kbd>Q</kbd><span>联结</span></button><button class="skill capture" data-action="capture" id="capture-button" aria-label="捕捉伊莫 E"><svg class="capture-progress" viewBox="0 0 100 100"><circle cx="50" cy="50" r="46"/></svg>${icon('orb')}<kbd>E</kbd><span id="capture-text">捕捉</span></button><div class="orb-count">联结球 <b id="orbs">20</b></div></div>
 <div class="prototype">非官方风格原型 · 单人探索</div><div class="bottom-right">${icon('leaf')} <span>让相遇，自然发生。</span></div>
 </div><div id="toast" class="toast"></div><div id="capture-reveal" class="capture-reveal"></div><div id="modal-root"></div><div class="photo-ui" hidden><span>风栖原野 <small>FIELD NOTES / 001</small></span><div><button data-action="snapshot">${icon('camera')} 保存照片</button><button data-action="photo">退出摄影 <kbd>P</kbd></button></div><p>拖动旋转镜头 · 滚轮缩放 · 世界已暂停</p></div><div class="touch-controls"><div id="joystick"><i></i></div><button data-action="jump">${icon('jump')}</button></div>`;
 this.root.addEventListener('click',e=>{const a=e.target.closest('[data-action]')?.dataset.action;if(a)this.action(a);const sp=e.target.closest('[data-species]')?.dataset.species;if(sp!==undefined)actions.select(Number(sp));const d=e.target.closest('[data-dex]')?.dataset.dex;if(d!==undefined){this.dexIndex=Number(d);this.renderModal('dex');}});
 this.mapCanvas=document.querySelector('#minimap');this.qCount=document.querySelector('#quest-count');this.qTitle=document.querySelector('#quest-title');this.qDetail=document.querySelector('#quest-detail');this.qHint=document.querySelector('#quest-hint');
 }
 action(a){if(['map','dex','pause','quest'].includes(a)){this.open(a);return;}if(a==='close'){this.close();return;}if(a==='continue'){this.close();return;}if(a==='photo'){this.togglePhoto();return;}if(a==='reset'){this.renderModal('reset');return;}if(a==='confirm-reset'){this.actions.reset();this.close();return;}this.actions[a]?.();}
 toast(text){const t=document.querySelector('#toast');t.textContent=text;t.classList.add('visible');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>t.classList.remove('visible'),3300);}
 reveal(index){const s=SPECIES[index],el=document.querySelector('#capture-reveal');el.innerHTML=`<img src="${this.portraits[index]}" alt="${s.name}"/><div><small>一段新的羁绊</small><strong>${s.name} 加入了旅途</strong><span>按 Q 联结合体 · ${s.ability}</span></div><i>✦</i>`;el.classList.add('visible');clearTimeout(this.revealTimer);this.revealTimer=setTimeout(()=>el.classList.remove('visible'),4200);}
 open(type){if(this.photo)this.togglePhoto();this.modal=type;this.root.classList.add('modal-open');this.state.paused=true;this.actions.release();this.renderModal(type);}
 close(){this.modal=null;this.root.classList.remove('modal-open');document.querySelector('#modal-root').innerHTML='';this.state.paused=false;this.actions.release();}
 togglePhoto(){if(this.modal)this.close();this.photo=!this.photo;this.state.paused=this.photo;document.querySelector('.hud').hidden=this.photo;document.querySelector('.photo-ui').hidden=!this.photo;this.root.classList.toggle('photographing',this.photo);this.actions.release();}
 renderModal(type){this.modal=type;const owned=uniqueSpecies(this.state),s=SPECIES[this.dexIndex];let content='',title='',eyebrow='';
 if(type==='dex'){title='每个相遇，都值得珍藏';eyebrow='ANIIMO FIELD GUIDE / 伊莫图鉴';content=`<div class="dex-layout"><div class="dex-showcase" style="--pet-color:${s.color}"><span class="dex-no">Nº 00${this.dexIndex+1}</span><span class="dex-element">${s.tag}属性</span><div class="portrait-orbit"></div><img src="${this.portraits[this.dexIndex]}" class="dex-hero ${owned.includes(this.dexIndex)?'':'undiscovered'}" alt="${s.name}"/><h2>${s.name}<small>${owned.includes(this.dexIndex)?'已联结 · 你的伙伴':'等待一次相遇'}</small></h2></div><div class="dex-details"><p class="section-kicker">原野档案 <span>${owned.length} / 4</span></p><div class="dex-grid">${SPECIES.map((p,i)=>`<button data-dex="${i}" class="dex-card ${this.dexIndex===i?'active':''}" style="--pet-color:${p.color}"><img src="${this.portraits[i]}" alt="${p.name}"/><span>${p.name}<small>${owned.includes(i)?'已结识 ✓':p.where}</small></span><b>0${i+1}</b></button>`).join('')}</div><div class="pet-description"><span>${s.where} / ${s.tag}</span><p>${s.note}</p><div>${icon('link')}<span>联结能力<strong>${s.ability}</strong></span>${owned.includes(this.dexIndex)?`<button class="pill-button" data-species="${this.dexIndex}">选为伙伴 ${icon('arrow')}</button>`:'<small>靠近野生伊莫，按 E 捕捉</small>'}</div></div></div></div>`;}
 if(type==='map'){title='下一段故事，去哪里？';eyebrow='WORLD MAP / 艾德尔探索地图';content=`<div class="map-layout"><div class="large-map"><canvas id="large-map" width="850" height="680"></canvas><div class="map-north">N ↑</div><div class="map-scale">──── 20 m</div></div><aside><p class="section-kicker">风栖原野 <span>01</span></p><h2>随风而行</h2><p class="map-copy">溪流、花海，还有不期而遇的伙伴。<br/>用自己的脚步，记住这片原野。</p><div class="map-legend"><p><i class="map-dot player"></i>你的位置</p><p><i class="map-dot pet"></i>野生伊莫</p><p><i class="map-dot gate"></i>风之门 · ${owned.length>=3?'可以启程':'结识3种伊莫后解锁'}</p></div><div class="map-progress">已结识的伙伴<strong>${owned.length}<small> / 4</small></strong><div><i style="width:${owned.length/4*100}%"></i></div></div><button class="primary" data-action="close">继续探索 ${icon('arrow')}</button></aside></div>`;}
 if(type==='pause'){title='不妨，停下来听听风';eyebrow='TAKE A BREATH / 旅途小憩';content=`<div class="settings-layout"><div class="pause-art">${icon('leaf')}<h2>世界很大<br/>慢慢来就好。</h2><p>你的旅途已自动保存。</p></div><div class="settings-list"><button data-action="sound"><span>${icon('sound')}原野音效</span><b id="sound-value">${this.actions.isSound()?'开启':'关闭'}</b></button><button data-action="quality"><span>${icon('sun')}画面质量</span><b id="quality-value">${this.actions.isHigh()?'精致':'流畅'}</b></button><button data-action="photo"><span>${icon('camera')}进入摄影模式</span><kbd>P</kbd></button><button data-action="reset"><span>${icon('reset')}重新开始旅途</span>${icon('arrow')}</button><div class="controls-note"><b>操作指南</b><p>WASD 移动 · Shift 疾跑 · 空格跳跃<br/>鼠标拖拽环视 · 滚轮缩放<br/>E 捕捉 / 交互 · Q 联结合体 · C 感知<br/>1—4 切换伙伴 · M 地图 · B 图鉴</p></div><button class="primary" data-action="close">回到原野 ${icon('arrow')}</button></div></div>`;}
 if(type==='quest'){title='与原野的伊莫成为伙伴';eyebrow='FIRST ENCOUNTER / 原野初遇';content=`<div class="quest-modal"><div class="quest-illustration">${this.portraits.map((p,i)=>`<img src="${p}" style="--i:${i}"/>`).join('')}</div><p>初次踏上艾德尔，不用急着奔向远方。<br/>先和这片原野上的小小居民，打个招呼吧。</p><ol><li class="${owned.length>=3?'done':''}">结识 3 种不同的伊莫 <b>${Math.min(owned.length,3)} / 3</b></li><li class="${this.state.completed?'done':''}">前往风之门，开启下一段旅程 <b>${this.state.completed?'已完成':'待启程'}</b></li></ol><div class="quest-rewards"><span>探索奖励</span><b>✦ 300 星屑</b><b>◉ 10 联结球</b></div><button class="primary" data-action="close">我准备好了 ${icon('arrow')}</button></div>`;}
 if(type==='complete'){title='最好的旅途，是有人同行';eyebrow='EXPEDITION COMPLETE / 原野初遇 · 完成';content=`<div class="completion"><div class="completion-emblem">${icon('spark')}</div><p>风之门记住了你和伙伴们的脚步。<br/>第一段探索圆满结束，而相遇还会继续。</p><div class="reward-row"><div><span>探索奖励</span><strong>300<small>星屑</small></strong></div><div><span>补给已入背包</span><strong>10<small>联结球</small></strong></div></div><button class="primary" data-action="continue">继续在原野漫游 ${icon('arrow')}</button><button class="text-button" data-action="reset">重新开始旅途</button></div>`;}
 if(type==='reset'){title='重新出发？';eyebrow='A NEW BEGINNING';content='<div class="confirm-reset"><p>这会清除本机的捕捉记录和探索进度。<br/>你将回到第一次踏上原野的清晨。</p><button class="primary" data-action="confirm-reset">确认重新开始</button><button class="text-button" data-action="close">保留当前旅途</button></div>';}
 document.querySelector('#modal-root').innerHTML=`<div class="modal-backdrop"><section class="modal ${type}"><header><div><p>${eyebrow}</p><h1>${title}</h1></div><button class="close-button" data-action="close" aria-label="关闭">${icon('close')}<kbd>Esc</kbd></button></header>${content}<footer><span>伊莫 · 风栖原野</span><span>LOCAL EXPLORATION / 非官方单人原型</span></footer></section></div>`;
 if(type==='map')this.drawMap(document.querySelector('#large-map'),false);
 }
 drawMap(canvas,mini=true){if(!canvas)return;const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.save();if(mini){ctx.beginPath();ctx.arc(w/2,h/2,w/2-6,0,Math.PI*2);ctx.clip();}ctx.fillStyle='#d8dfb6';ctx.fillRect(0,0,w,h);const zoom=mini?2.4:5.4,cx=mini?this.state.x:0,cz=mini?this.state.z:-10;const to=(x,z)=>[w/2+(x-cx)*zoom,h/2+(z-cz)*zoom];
 // The map samples the same terrain and river as the game.
 for(let y=0;y<h;y+=7)for(let x=0;x<w;x+=7){const wx=(x-w/2)/zoom+cx,wz=(y-h/2)/zoom+cz,hh=heightAt(wx,wz);const l=68+hh*1.3;ctx.fillStyle=`hsl(${87+hh},${23+hh}%,${Math.min(80,l)}%)`;ctx.fillRect(x,y,7,7);}
 for(let j=0;j<8;j++){ctx.beginPath();for(let z=-170;z<180;z+=2){const x=-70+j*20+Math.sin(z*.035+j)*8;const [a,b]=to(x,z);z===-170?ctx.moveTo(a,b):ctx.lineTo(a,b);}ctx.strokeStyle='#93ab7035';ctx.lineWidth=1.5;ctx.stroke();}
 ctx.beginPath();for(let z=-180;z<180;z+=2){const[a,b]=to(riverX(z),z);z===-180?ctx.moveTo(a,b):ctx.lineTo(a,b);}ctx.strokeStyle='#a8c9be';ctx.lineWidth=14*zoom;ctx.stroke();ctx.strokeStyle='#7bbaC7';ctx.lineWidth=10*zoom;ctx.stroke();
 ctx.beginPath();for(let z=-65;z<=28;z++){const[a,b]=to(-3+Math.sin(z*.045)*5,z);z===-65?ctx.moveTo(a,b):ctx.lineTo(a,b);}ctx.strokeStyle='#f4ecc9';ctx.lineWidth=3*zoom;ctx.stroke();
 if(!mini){ctx.fillStyle='#5c725c';ctx.font='500 20px system-ui';for(const [label,x,z] of [['风语林地',-39,-47],['映蓝河湾',37,-19],['初遇花甸',-18,28],['日光小径',8,-18]]){const[a,b]=to(x,z);ctx.fillText(label,a-30,b);}}
 for(const pet of WILD){if(this.state.captured.includes(pet.id))continue;const[a,b]=to(pet.x,pet.z);ctx.fillStyle=SPECIES[pet.species].accent;ctx.strokeStyle='#fbfff0';ctx.lineWidth=mini?2:3;ctx.beginPath();ctx.arc(a,b,mini?4.5:7,0,Math.PI*2);ctx.fill();ctx.stroke();}
 const[px,py]=to(PORTAL.x,PORTAL.z);ctx.save();ctx.translate(px,py);ctx.rotate(Math.PI/4);ctx.fillStyle='#fff1b0';ctx.strokeStyle='#ac925b';ctx.lineWidth=2;ctx.fillRect(-6,-6,12,12);ctx.strokeRect(-6,-6,12,12);ctx.restore();
 const[a,b]=to(this.state.x,this.state.z);ctx.save();ctx.translate(a,b);ctx.rotate(-this.state.yaw+Math.PI);ctx.fillStyle='#fffceb';ctx.strokeStyle='#496c68';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,-11);ctx.lineTo(7,8);ctx.lineTo(0,5);ctx.lineTo(-7,8);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();ctx.restore();
 }
 update(time,near,project,portalDistance){const s=this.state,owned=uniqueSpecies(s);this.qCount.textContent=`${Math.min(owned.length,3)} / 3`;this.qTitle.textContent=s.completed?'每一次相遇，都是新的开始':owned.length>=3?'循着微风，前往风之门':'与原野的伊莫成为伙伴';this.qDetail.textContent=s.completed?'原野初遇已完成':owned.length>=3?'抵达风之门并按 E 启程':'结识 3 种不同的伊莫';this.qHint.textContent=s.completed?'继续漫游，寻找还未相遇的伙伴':owned.length>=3?`风之门距你 ${Math.round(portalDistance)} m`:'沿着花香，寻找新的相遇';document.querySelector('#discover').textContent=owned.length;document.querySelector('#orbs').textContent=s.orbs;document.querySelector('#steps').textContent=`${Math.round(s.steps)} m`;
 document.querySelectorAll('.partner').forEach((el,i)=>{el.classList.toggle('locked',!owned.includes(i));el.classList.toggle('selected',s.selected===i&&owned.includes(i));});document.querySelector('#player-name').textContent=s.twined?SPECIES[s.selected].name:'原野旅人';document.querySelector('#player-form').textContent=s.twined?'联结形态':'探索者';document.querySelector('#twine-button').classList.toggle('active',s.twined);document.querySelector('#twine-status span').textContent=s.twined?`正在联结 · ${SPECIES[s.selected].ability} · Q 解除`:owned.length?'按 Q 与伙伴联结，感受不一样的原野':'与伊莫联结，发现另一种可能';
 const label=document.querySelector('#target-label');if(near&&!s.twined&&!s.capture&&!s.paused){const p=project(near.x,near.y+1.85,near.z);label.hidden=!p.visible;if(p.visible){label.style.left=p.x+'px';label.style.top=p.y+'px';document.querySelector('#target-name').textContent=SPECIES[near.species].name;document.querySelector('#target-element').textContent=SPECIES[near.species].tag;}}else label.hidden=true;
 const ready=owned.length>=3&&portalDistance<7&&!s.completed;document.querySelector('#capture-text').textContent=s.capture?'联结中':ready?'启程':'捕捉';document.querySelector('#capture-button').classList.toggle('available',!!near||ready);document.querySelector('.capture-progress circle').style.strokeDashoffset=289*(1-(s.capture?.progress||0));
 const way=document.querySelector('#waypoint');if(owned.length>=3&&!s.completed){const p=project(PORTAL.x,heightAt(PORTAL.x,PORTAL.z)+7.5,PORTAL.z);way.hidden=!p.visible;way.style.left=p.x+'px';way.style.top=p.y+'px';way.querySelector('b').textContent=Math.round(portalDistance)+' m';}else way.hidden=true;
 if(time-this.lastMap>.1){this.drawMap(this.mapCanvas);if(this.modal==='map')this.drawMap(document.querySelector('#large-map'),false);this.lastMap=time;}
 }
}
