import {createRequire} from 'node:module';
import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import crypto from 'node:crypto';
export const skill=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
export function args(argv=process.argv.slice(2)){const out={};for(let i=0;i<argv.length;i++){if(!argv[i].startsWith('--')||!argv[i+1]||argv[i+1].startsWith('--'))throw Error('Expected --key value arguments');out[argv[i].slice(2)]=argv[++i];}return out;}
export function required(a,name){if(!a[name])throw Error('Missing --'+name);return path.resolve(a[name]);}
export function sha(file){return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');}
export function fresh(dir){dir=path.resolve(dir);let ancestor=dir;while(!fs.existsSync(ancestor))ancestor=path.dirname(ancestor);const real=path.join(fs.realpathSync(ancestor),path.relative(ancestor,dir));if(real===skill||real.startsWith(skill+path.sep))throw Error('Output must be outside the Skill');if(fs.existsSync(dir)&&(!fs.statSync(dir).isDirectory()||fs.readdirSync(dir).length))throw Error('Refusing nonempty output: '+dir);fs.mkdirSync(dir,{recursive:true});return dir;}
export function chrome(){const candidates=[process.env.CHROME_PATH];if(process.platform==='darwin')candidates.push('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome');else if(process.platform==='win32'){for(const base of[process.env.PROGRAMFILES,process.env['PROGRAMFILES(X86)'],process.env.LOCALAPPDATA].filter(Boolean)){candidates.push(path.join(base,'Google/Chrome/Application/chrome.exe'),path.join(base,'Microsoft/Edge/Application/msedge.exe'));}}else candidates.push('/usr/bin/google-chrome','/usr/bin/google-chrome-stable','/usr/bin/chromium','/usr/bin/chromium-browser');const found=candidates.find(p=>p&&fs.existsSync(p));if(!found)throw Error('Chrome not found. Set CHROME_PATH to a WebGL-capable Chrome/Chromium executable. No browser is auto-installed.');return found;}
export function browserOptions(){return{executablePath:chrome(),headless:true,args:[...(process.platform==='darwin'?['--use-angle=metal']:[]),'--allow-file-access-from-files']};}

export function projectRequire(project){const p=path.resolve(project);if(p===skill||p.startsWith(skill+path.sep))throw Error('Use an output project outside the skill');const tools=path.join(p,'tooling/package.json');if(!fs.existsSync(tools))throw Error('Optional tests need output/tooling: copy the skill package.json and package-lock.json there, then npm ci in tooling');return createRequire(tools);}
