import { chromium } from '@playwright/test';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const url=process.env.TEST_URL || 'http://127.0.0.1:5173/?test=1';
await fs.mkdir('screenshots',{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist','--use-angle=metal']});
const page=await browser.newPage({viewport:{width:1600,height:1000},deviceScaleFactor:1});
const errors=[],warnings=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('console',m=>{if(m.type()==='error')errors.push(m.text());if(m.type()==='warning')warnings.push(m.text());});
console.log('Loading',url);
await page.goto(url,{waitUntil:'commit',timeout:180000});
for(let i=0;i<60;i++){try{if(await page.evaluate(()=>window.__ready))break;}catch(e){if(!e.message.includes('context was destroyed'))throw e;}await new Promise(r=>setTimeout(r,500));}
assert(await page.evaluate(()=>window.__ready));
await new Promise(r=>setTimeout(r,1600));
console.log('MENU',await page.evaluate(()=>window.__game.stats));
await page.screenshot({path:'screenshots/01-menu.png'});
assert.equal(await page.locator('[data-character]').count(),6);
await page.locator('[data-character="mango"]').click({force:true});
assert.equal(await page.evaluate(()=>window.__game.snapshot.racers[0].characterId),'mango');
await page.locator('[data-character="mochi"]').click({force:true});
await page.locator('[data-action="help"]').first().click({force:true});
assert.equal(await page.locator('dialog').evaluate(e=>e.open),true);
await page.locator('[data-action="close-dialog"]').click({force:true});
await page.locator('[data-action="start"]').click({force:true});
assert.equal(await page.evaluate(()=>window.__game.snapshot.phase),'countdown');
await page.evaluate(()=>window.__game.step(3.1,{}));
await page.keyboard.down('w');await new Promise(r=>setTimeout(r,2000));await page.keyboard.up('w');
const moving=await page.evaluate(()=>({speed:window.__game.snapshot.speed,progress:window.__game.snapshot.racers[0].progress}));
assert(moving.speed>0,`keyboard acceleration failed ${JSON.stringify(moving)}`);
console.log('KEYBOARD',moving);
// Forward-only world heading MUST not become involuntary autopilot.
await page.keyboard.down('d');await page.keyboard.down('w');await new Promise(r=>setTimeout(r,700));await page.keyboard.up('d');await page.keyboard.up('w');
await page.keyboard.press('r');await new Promise(r=>setTimeout(r,150));
await page.evaluate(()=>window.__game.step(5,{assist:true,throttle:1}));
await new Promise(r=>setTimeout(r,200));
await page.screenshot({path:'screenshots/02-race.png'});
await page.keyboard.press('Escape');
assert.equal(await page.evaluate(()=>window.__game.snapshot.phase),'paused');
const paused=await page.evaluate(()=>window.__game.snapshot.elapsed);
await new Promise(r=>setTimeout(r,350));
assert.equal(await page.evaluate(()=>window.__game.snapshot.elapsed),paused);
await page.screenshot({path:'screenshots/03-pause.png'});
await page.locator('[data-action="resume"]').click({force:true});
assert.equal(await page.evaluate(()=>window.__game.snapshot.phase),'racing');
// Items, drift and laps have their own unit suite; here verify end-to-end finish/UI.
const finished=await page.evaluate(()=>{
 const g=window.__game;for(let i=0;i<45 && g.snapshot.phase!=='finished';i++)g.step(10,{throttle:1,assist:true,item:i%2===0});
 return {phase:g.snapshot.phase,elapsed:g.snapshot.elapsed,lap:g.snapshot.lap,position:g.snapshot.position,results:g.snapshot.results,stats:g.stats};
});
console.log('FINISH',JSON.stringify(finished));
assert.equal(finished.phase,'finished');assert.equal(finished.results.length,8);
await new Promise(r=>setTimeout(r,300));await page.screenshot({path:'screenshots/04-results.png'});
await page.locator('[data-ui="results"] [data-action="menu"]').click({force:true});
assert.equal(await page.evaluate(()=>window.__game.snapshot.phase),'menu');
await page.keyboard.press('p');assert(await page.locator('body').evaluate(e=>e.classList.contains('photo-mode')));
await page.screenshot({path:'screenshots/05-postcard.png'});await page.keyboard.press('p');
await page.setViewportSize({width:390,height:844});await new Promise(r=>setTimeout(r,500));await page.screenshot({path:'screenshots/06-mobile-menu.png'});
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
assert.equal(overflow,false,'mobile overflow');
await page.locator('[data-action="start"]').click({force:true});await page.evaluate(()=>window.__game.step(3.1,{}));await new Promise(r=>setTimeout(r,500));
await page.screenshot({path:'screenshots/07-mobile-race.png'});
console.log('ERRORS',errors);console.log('WARNINGS',warnings);
await fs.writeFile('tests/browser-report.json',JSON.stringify({errors,warnings,moving,finished,mobileOverflow:overflow},null,2));
await browser.close();assert.equal(errors.length,0,errors.join('\n'));console.log('All browser smoke checks passed.');
