import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--use-angle=metal','--enable-webgl','--ignore-gpu-blocklist']});
const context=await browser.newContext({viewport:{width:1440,height:900},deviceScaleFactor:1,acceptDownloads:true});const page=await context.newPage();const errors=[],requests=[],checks=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('response',r=>{if(r.status()>=400)requests.push({url:r.url(),status:r.status()});});const snapshot=()=>page.evaluate(()=>window.__ANIIMO__.snapshot());const check=(name,value)=>{assert.ok(value,name);checks.push(name);console.log('PASS',name);};
try{
 await page.goto(process.env.TEST_URL||'http://127.0.0.1:4318');await page.waitForFunction(()=>window.__ANIIMO__);await page.waitForTimeout(2200);let s=await snapshot();check('Fresh playable world and zero fake companions',!s.paused&&s.owned.length===0);await page.keyboard.press('e');check('Distant capture rejected',(await snapshot()).orbs===20);
 await page.keyboard.down('w');await page.waitForTimeout(1400);await page.keyboard.up('w');let moved=await snapshot();check('Real WASD input moves toward a creature',moved.z<s.z-3);await page.waitForTimeout(300);check('Nearby wild target acquired',!!(await snapshot()).near);await page.screenshot({path:'reports/03-encounter.png'});
 await page.keyboard.press('e');await page.waitForFunction(()=>window.__ANIIMO__.snapshot().captured.length===1);s=await snapshot();check('Capture updates world, inventory, and stock exactly once',s.captured[0]==='c1'&&s.orbs===19);await page.screenshot({path:'reports/04-captured.png'});
 await page.keyboard.press('q');check('Q enters actual linked form',(await snapshot()).twined);const y=(await snapshot()).y;await page.keyboard.press('Space');await page.waitForTimeout(250);check('Linked pet can jump',(await snapshot()).y>y+.4);await page.keyboard.press('Space');await page.waitForTimeout(200);check('Cloud link has a real second jump',(await snapshot()).vy>0);await page.screenshot({path:'reports/05-linked.png'});await page.keyboard.press('q');await page.waitForTimeout(1000);
 await page.keyboard.press('Escape');s=await snapshot();await page.waitForTimeout(500);check('Pause freezes simulation time',(await snapshot()).time===s.time);await page.keyboard.down('w');await page.waitForTimeout(200);await page.keyboard.up('w');check('Paused keyboard cannot move the player',(await snapshot()).z===s.z);await page.keyboard.press('Escape');
 await page.mouse.move(810,450);s=await snapshot();await page.mouse.down({button:'right'});await page.mouse.move(960,500,{steps:8});await page.mouse.up({button:'right'});check('Dragging orbits the camera',Math.abs((await snapshot()).camera.yaw-s.camera.yaw)>.3);
 // Test fixtures place the player near otherwise normal wild creatures; captures use real E input.
 for(const id of ['f1','a1']){const p=await page.evaluate(id=>window.__ANIIMO__.world().wild.find(w=>w.id===id),id);await page.evaluate(p=>window.__ANIIMO__.teleport(p.x,p.z+4),p);await page.waitForTimeout(300);await page.keyboard.press('e');await page.waitForFunction(id=>window.__ANIIMO__.snapshot().captured.includes(id),id);}
 s=await snapshot();check('Three distinct species progress the expedition',s.owned.length===3&&!s.completed);await page.keyboard.press('2');check('Number key switches captured companion',(await snapshot()).selected===1);await page.keyboard.press('q');check('Fox linked form selected',(await snapshot()).twined);await page.keyboard.press('q');
 await page.keyboard.press('m');await page.waitForTimeout(300);check('World map shows actual exploration progress',await page.locator('.map-progress strong').textContent()==='3 / 4');await page.screenshot({path:'reports/06-map.png'});await page.keyboard.press('Escape');await page.keyboard.press('b');await page.waitForTimeout(300);check('Dex lists owned creatures',(await page.locator('.dex-card').filter({hasText:'已结识'}).count())===3);await page.screenshot({path:'reports/07-owned-dex.png'});await page.keyboard.press('Escape');
 await page.evaluate(()=>{const p=window.__ANIIMO__.world().portal;window.__ANIIMO__.teleport(p.x,p.z+4);});await page.waitForTimeout(300);await page.keyboard.press('e');s=await snapshot();check('Portal delivers quest reward and completion once',s.completed&&s.reward===300&&s.orbs===27);await page.waitForTimeout(300);await page.screenshot({path:'reports/08-complete.png'});await page.getByRole('button',{name:/继续在原野漫游/}).click();await page.keyboard.press('e');check('Repeated portal submission cannot duplicate rewards',(await snapshot()).reward===300&&(await snapshot()).orbs===27);
 await page.reload();await page.waitForFunction(()=>window.__ANIIMO__);check('Reload restores completed expedition and collection',(await snapshot()).completed&&(await snapshot()).captured.length===3);
 await page.keyboard.press('p');s=await snapshot();await page.waitForTimeout(200);check('Photography freezes gameplay',(await snapshot()).time===s.time);const d=page.waitForEvent('download');await page.getByRole('button',{name:'保存照片'}).click();const download=await d;await download.saveAs('reports/photo-export.png');check('Photography exports a real PNG',(await fs.stat('reports/photo-export.png')).size>10000);await page.keyboard.press('p');
 await page.keyboard.press('Escape');await page.getByRole('button',{name:'重新开始旅途'}).click();await page.getByRole('button',{name:'确认重新开始'}).click();s=await snapshot();check('Confirmed restart clears collection, reward and inventory',s.captured.length===0&&!s.completed&&s.orbs===20&&s.x===0&&s.z===19);await page.reload();await page.waitForFunction(()=>window.__ANIIMO__);check('Restart persists without resurrecting old save',(await snapshot()).captured.length===0);
 await page.keyboard.down('w');await page.waitForTimeout(200);await page.evaluate(()=>window.dispatchEvent(new Event('blur')));s=await snapshot();await page.waitForTimeout(300);check('Window blur releases held movement',(await snapshot()).z===s.z);await page.keyboard.up('w');
 check('No JS errors or failed HTTP assets',errors.length===0&&requests.length===0);await page.evaluate(()=>window.__ANIIMO__.actions.reset());await page.waitForTimeout(600);await page.screenshot({path:'reports/01-first-look.png'});const perf=await snapshot();
 await fs.writeFile('reports/browser-report.json',JSON.stringify({date:new Date().toISOString(),checks,errors,requests,performance:{fps:perf.fps,drawCalls:perf.drawCalls,triangles:perf.triangles},environment:'Headless Chrome / macOS / ANGLE Metal / 1440x900 DPR1',fixtureNote:'f1/a1/portal reached via DEV teleport fixture; keyboard movement, first capture, all capture actions, jump, pause, save, UI, reward and export exercised through real inputs.'},null,2));
 console.log(`Passed ${checks.length} checks`);
}finally{await browser.close();}
