import './style.css';
import * as T from 'three';
import {createWorld} from './world.js';
import {makeExplorer,makePet,createPortraits} from './actors.js';
import {heightAt,riverDist} from './terrain.js';
import {createState,readSave,save,SPECIES,WILD,PORTAL,uniqueSpecies,startCapture,stepCapture,toggleTwine,selectSpecies,completeQuest} from './state.js';
import {UI} from './ui.js';
import {Input} from './input.js';
import {Audio} from './audio.js';
async function boot(){
 const canvas=document.querySelector('#world');const renderer=new T.WebGLRenderer({canvas,antialias:true,alpha:false,preserveDrawingBuffer:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;renderer.outputColorSpace=T.SRGBColorSpace;
 const scene=new T.Scene(),camera=new T.PerspectiveCamera(52,innerWidth/innerHeight,.1,1000);const world=createWorld(scene);let state=readSave(localStorage);state.y=Math.max(.25,heightAt(state.x,state.z));
 const explorer=makeExplorer();scene.add(explorer.root);const wild=WILD.map(w=>{const actor=makePet(w.species,w.species===0?1.02:1);const p={...w,actor,x:w.x,z:w.z,y:Math.max(.3,heightAt(w.x,w.z))};actor.root.position.set(p.x,p.y,p.z);actor.root.rotation.y=Math.PI*.7;actor.root.visible=!state.captured.includes(w.id);scene.add(actor.root);return p;});
 const portraits=createPortraits(renderer);let companion=makePet(state.selected,.8),form=makePet(state.selected,1.6);scene.add(companion.root,form.root);companion.root.position.set(state.x+1.5,state.y,state.z+1);
 let camYaw=.02,camPitch=.105,camDistance=8.6;let near=null,input,ui;let high=true;let lastSave=0,wallTime=0,frameCount=0,frameWindow=0,actualFPS=0,jumpCount=0;const audio=new Audio();const pointer=new T.Vector3(),camPos=new T.Vector3(),target=new T.Vector3(),vec=new T.Vector3();
 const captureOrb=new T.Mesh(new T.SphereGeometry(.14,20,12),new T.MeshStandardMaterial({color:'#f4f6cc',emissive:'#c8efa6',emissiveIntensity:2}));scene.add(captureOrb);captureOrb.visible=false;
 const ring=new T.Mesh(new T.TorusGeometry(.75,.025,6,56),new T.MeshBasicMaterial({color:'#f7ffc0',transparent:true,opacity:.8}));ring.rotation.x=-Math.PI/2;scene.add(ring);ring.visible=false;
 const scanRing=new T.Mesh(new T.RingGeometry(.98,1,100),new T.MeshBasicMaterial({color:'#e9f9c0',transparent:true,opacity:.5,side:T.DoubleSide,depthWrite:false}));scanRing.rotation.x=-Math.PI/2;scene.add(scanRing);scanRing.visible=false;let scanTime=-100;
 const sparks=[];function burst(x,y,z,color='#e6ffc5',amount=36){for(let i=0;i<amount;i++){const m=new T.Mesh(new T.OctahedronGeometry(.045+Math.random()*.05),new T.MeshBasicMaterial({color,transparent:true,opacity:1}));m.position.set(x,y,z);scene.add(m);sparks.push({m,v:new T.Vector3((Math.random()-.5)*4,1+Math.random()*3,(Math.random()-.5)*4),life:1.1});}}
 function replacePets(){for(const p of [companion,form])p.root.traverse(m=>{if(m.isMesh)m.geometry.dispose();});scene.remove(companion.root,form.root);companion=makePet(state.selected,.8);form=makePet(state.selected,1.6);scene.add(companion.root,form.root);companion.root.position.set(state.x+1,state.y,state.z);}
 function attemptCapture(){if(state.paused)return;if(Math.hypot(state.x-PORTAL.x,state.z-PORTAL.z)<7){if(completeQuest(state,Math.hypot(state.x-PORTAL.x,state.z-PORTAL.z))){audio.play('complete');save(state,localStorage);burst(PORTAL.x,heightAt(PORTAL.x,PORTAL.z)+3,PORTAL.z,'#fff0a0',80);ui.open('complete');return;}if(uniqueSpecies(state).length<3){ui.toast('风之门还在等待：先结识 3 种不同的伊莫');return;}}
 if(state.twined){ui.toast('按 Q 解除联结，再向新伙伴投出联结球');return;}if(state.capture)return;if(!near){ui.toast('再靠近一点吧 · 在伊莫 8 米内按 E 捕捉');audio.play('error');return;}if(startCapture(state,near.id,Math.hypot(state.x-near.x,state.z-near.z))){audio.play('select');}}
 function jump(){if(state.paused||state.capture)return;const max=state.twined&&[0,3].includes(state.selected)?2:1;if(jumpCount>=max)return;state.vy=jumpCount>0?6.8:state.twined?8:6.1;jumpCount++;audio.play('jump');if(jumpCount>1)burst(state.x,state.y+.4,state.z);}
 const actions={capture:attemptCapture,twine(){if(toggleTwine(state)){replacePets();burst(state.x,state.y+1,state.z,SPECIES[state.selected].color,45);audio.play('twine');ui.toast(state.twined?`与${SPECIES[state.selected].name}联结了 · ${SPECIES[state.selected].ability}`:'解除联结 · 欢迎回来，旅人');}else if(!state.paused)ui.toast('先与一只伊莫成为伙伴，再按 Q 联结合体');},scan(){if(state.paused)return;scanTime=state.time;scanRing.position.set(state.x,state.y+.1,state.z);const closest=wild.filter(w=>!state.captured.includes(w.id)).sort((a,b)=>Math.hypot(a.x-state.x,a.z-state.z)-Math.hypot(b.x-state.x,b.z-state.z))[0];ui.toast(closest?`感知到${SPECIES[closest.species].name}的气息 · ${Math.round(Math.hypot(closest.x-state.x,closest.z-state.z))} 米 · 打开 M 查看地图`:'这片原野的伊莫都与你相遇了，去风之门看看吧');audio.play('scan');},select(i){if(state.capture)return;if(selectSpecies(state,i)){replacePets();audio.play('select');if(ui.modal==='dex')ui.toast(`已选择 ${SPECIES[i].name} 作为伙伴`);}else ui.toast(`还没有结识${SPECIES[i].name} · 去${SPECIES[i].where}找找吧`);},jump,
 reset(){Object.assign(state,createState());state.y=Math.max(.3,heightAt(state.x,state.z));wild.forEach(w=>w.actor.root.visible=true);camYaw=.02;camPitch=.105;camDistance=8.6;replacePets();input.release();jumpCount=0;captureOrb.visible=false;scanRing.visible=false;scanTime=-100;lastSave=0;sparks.forEach(p=>{scene.remove(p.m);p.m.geometry.dispose();p.m.material.dispose();});sparks.length=0;save(state,localStorage);ui.toast('新的清晨，新的旅途。');},release(){input?.release();},sound(){const on=audio.toggle();const el=document.querySelector('#sound-value');if(el)el.textContent=on?'开启':'关闭';},quality(){high=!high;world.quality(high);renderer.setPixelRatio(Math.min(devicePixelRatio,high?1.7:1));const el=document.querySelector('#quality-value');if(el)el.textContent=high?'精致':'流畅';},isHigh:()=>high,isSound:()=>audio.enabled,
 snapshot(){renderer.render(scene,camera);const a=document.createElement('a');a.download='风栖原野-'+Date.now()+'.png';a.href=canvas.toDataURL('image/png');a.click();ui.toast('已保存这一刻 · 照片不包含界面');}};
 ui=new UI(state,portraits,actions);input=new Input(canvas,a=>{if(a==='escape'){if(ui.photo)ui.togglePhoto();else if(ui.modal)ui.close();else ui.open('pause');return;}if(a==='photo'){ui.togglePhoto();return;}if(['map','dex'].includes(a)){if(ui.modal===a)ui.close();else ui.open(a);return;}if(a.startsWith('select')){if(!state.paused)actions.select(Number(a.slice(-1)));return;}if(!state.paused)actions[a]?.();},(dx,dy)=>{if(ui.modal)return;camYaw+=dx;camPitch=T.MathUtils.clamp(camPitch+dy,.08,1.1);},d=>{if(!ui.modal)camDistance=T.MathUtils.clamp(camDistance+d,4,19);});input.joystick();
 const project=(x,y,z)=>{pointer.set(x,y,z).project(camera);return{x:(pointer.x*.5+.5)*innerWidth,y:(-.5*pointer.y+.5)*innerHeight,visible:pointer.z<1&&pointer.z>-1&&Math.abs(pointer.x)<.96&&Math.abs(pointer.y)<.9};};
 const walkHeight=(x,z)=>Math.max(state.twined&&state.selected===2?.34:.13,heightAt(x,z));
 function setCamera(dt,immediate=false){const shoulder=state.twined?.35:1.15;target.set(state.x+Math.cos(camYaw)*shoulder,state.y+(state.twined?2.1:2.65),state.z-Math.sin(camYaw)*shoulder);camPos.set(target.x+Math.sin(camYaw)*Math.cos(camPitch)*camDistance,target.y+Math.sin(camPitch)*camDistance,target.z+Math.cos(camYaw)*Math.cos(camPitch)*camDistance);camPos.y=Math.max(camPos.y,heightAt(camPos.x,camPos.z)+1.2);camera.position.lerp(camPos,immediate?1:1-Math.exp(-dt*10));camera.lookAt(target);}
 setCamera(0,true);
 let last=performance.now();function loop(now){const rawDt=(now-last)/1000;const dt=Math.min(rawDt,.05);last=now;wallTime+=rawDt;frameCount++;frameWindow+=rawDt;if(frameWindow>=1){actualFPS=frameCount/frameWindow;frameCount=0;frameWindow=0;}
 if(!state.paused){state.time+=dt;const axis=input.axes();let speed=axis.sprint?7.2:4.6;if(state.twined)speed=state.selected===1?11.5:7.8;if(riverDist(state.x,state.z)<5&&heightAt(state.x,state.z)<.3&&!(state.twined&&state.selected===2))speed*=.46;if(state.capture)speed=0;
 const dx=(axis.x*Math.cos(camYaw)+axis.z*Math.sin(camYaw))*speed*dt,dz=(-axis.x*Math.sin(camYaw)+axis.z*Math.cos(camYaw))*speed*dt;const moving=Math.hypot(dx,dz)>.001;
 let nx=T.MathUtils.clamp(state.x+dx,-67,67),nz=T.MathUtils.clamp(state.z+dz,-87,64);for(const o of world.obstacles){const d=Math.hypot(nx-o.x,nz-o.z),r=o.r+.3;if(d<r&&d>0){nx=o.x+(nx-o.x)/d*r;nz=o.z+(nz-o.z)/d*r;}}
 state.steps+=Math.hypot(nx-state.x,nz-state.z);state.x=nx;state.z=nz;if(moving){const wanted=Math.atan2(dx,dz);state.yaw+=Math.atan2(Math.sin(wanted-state.yaw),Math.cos(wanted-state.yaw))*Math.min(1,dt*12);}
 const ground=walkHeight(state.x,state.z);state.vy-=18*dt;state.y+=state.vy*dt;if(state.y<=ground){state.y=ground;state.vy=0;jumpCount=0;}
 explorer.root.position.set(state.x,state.y,state.z);explorer.root.rotation.y=state.yaw;explorer.root.visible=!state.twined;explorer.update(state.time,moving,jumpCount>0,!!state.capture);form.root.position.copy(explorer.root.position);form.root.rotation.y=state.yaw;form.root.visible=state.twined;form.update(state.time,moving);
 const owned=uniqueSpecies(state);companion.root.visible=owned.length>0&&!state.twined;const tx=state.x-Math.sin(state.yaw)*2+Math.cos(state.yaw)*1.05,tz=state.z-Math.cos(state.yaw)*2-Math.sin(state.yaw)*1.05;const cd=Math.hypot(companion.root.position.x-tx,companion.root.position.z-tz);companion.root.position.x=T.MathUtils.lerp(companion.root.position.x,tx,1-Math.exp(-dt*3));companion.root.position.z=T.MathUtils.lerp(companion.root.position.z,tz,1-Math.exp(-dt*3));companion.root.position.y=Math.max(.28,heightAt(companion.root.position.x,companion.root.position.z));if(cd>.1)companion.root.rotation.y=Math.atan2(tx-companion.root.position.x,tz-companion.root.position.z);companion.update(state.time,cd>.5);
 for(const w of wild){w.actor.root.visible=!state.captured.includes(w.id);if(!w.actor.root.visible)continue;const caught=state.capture?.id===w.id;const dist=Math.hypot(w.x-state.x,w.z-state.z);if(!caught){const base=WILD.find(v=>v.id===w.id);w.x=base.x+Math.sin(state.time*.21+w.phase)*.75;w.z=base.z+Math.cos(state.time*.18+w.phase)*.75;w.y=Math.max(.31,heightAt(w.x,w.z));}w.actor.root.position.set(w.x,w.y,w.z);w.actor.root.rotation.y=dist<9?Math.atan2(state.x-w.x,state.z-w.z):Math.sin(state.time*.18+w.phase)*.9+w.phase;w.actor.update(state.time+w.phase,false);w.actor.root.scale.setScalar(caught?1-Math.max(0,state.capture.progress-.75)*3:1);}
 near=wild.filter(w=>!state.captured.includes(w.id)).sort((a,b)=>Math.hypot(a.x-state.x,a.z-state.z)-Math.hypot(b.x-state.x,b.z-state.z))[0];if(near&&Math.hypot(near.x-state.x,near.z-state.z)>8)near=null;
 ring.visible=!!near&&!state.twined&&!state.capture;if(ring.visible){ring.position.set(near.x,near.y+.07,near.z);ring.scale.setScalar(.9+Math.sin(state.time*3)*.05);}
 captureOrb.visible=!!state.capture;if(state.capture){const w=wild.find(v=>v.id===state.capture.id),p=Math.min(1,state.capture.progress*2.6);captureOrb.position.set(T.MathUtils.lerp(state.x,w.x,p),T.MathUtils.lerp(state.y+1.45,w.y+.8,p)+Math.sin(p*Math.PI)*2.2,T.MathUtils.lerp(state.z,w.z,p));captureOrb.scale.setScalar(.9+Math.sin(state.time*20)*.2);}
 const caught=stepCapture(state,dt);if(caught!==null){const lastPet=wild.find(w=>w.id===state.captured.at(-1));lastPet.actor.root.visible=false;burst(lastPet.x,lastPet.y+.8,lastPet.z,SPECIES[caught].color);replacePets();ui.reveal(caught);audio.play('capture');save(state,localStorage);}
 scanRing.visible=state.time-scanTime<1.7;if(scanRing.visible){const p=(state.time-scanTime)/1.7;scanRing.scale.setScalar(p*35+.1);scanRing.material.opacity=(1-p)*.55;}
 for(let i=sparks.length-1;i>=0;i--){const p=sparks[i];p.life-=dt;p.m.position.addScaledVector(p.v,dt);p.v.y-=dt*2;p.m.rotation.x+=dt*2;p.m.material.opacity=Math.max(0,p.life);if(p.life<=0){scene.remove(p.m);p.m.geometry.dispose();p.m.material.dispose();sparks.splice(i,1);}}
 world.update(state.time);if(state.time-lastSave>6){save(state,localStorage);lastSave=state.time;}
 }
 setCamera(dt);ui.update(wallTime,near,project,Math.hypot(state.x-PORTAL.x,state.z-PORTAL.z));renderer.render(scene,camera);requestAnimationFrame(loop);
 }
 window.addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();});window.addEventListener('beforeunload',()=>save(state,localStorage));window.addEventListener('blur',()=>{input.release();save(state,localStorage);});document.addEventListener('visibilitychange',()=>{if(document.hidden&&!ui.modal&&!ui.photo)ui.open('pause');});
 // Fixture controls exist ONLY in Vite dev builds; production remains a regular playable game.
 if(import.meta.env.DEV){window.__ANIIMO__={snapshot:()=>({...state,owned:uniqueSpecies(state),fps:actualFPS,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,camera:{yaw:camYaw,pitch:camPitch,distance:camDistance},near:near?.id}),teleport(x,z){state.x=x;state.z=z;state.y=Math.max(.3,heightAt(x,z));state.vy=0;jumpCount=0;setCamera(0,true);},actions,world:()=>({wild:wild.map(w=>({id:w.id,x:w.x,y:w.y,z:w.z})),portal:PORTAL}),setCamera(yaw,pitch,distance){camYaw=yaw;camPitch=pitch;camDistance=distance;setCamera(0,true);}};}
 requestAnimationFrame(loop);document.querySelector('#loading').classList.add('loaded');setTimeout(()=>document.querySelector('#loading')?.remove(),850);setTimeout(()=>ui.toast('欢迎来到风栖原野 · WASD 出发，靠近伊莫按 E'),1100);
}
boot().catch(e=>{console.error(e);document.querySelector('#loading').innerHTML='<h1>原野暂时没有醒来</h1><p>请使用支持 WebGL2 的浏览器，或开启硬件加速后刷新。</p><pre></pre>';document.querySelector('#loading pre').textContent=e.message;});
