import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
export function args(){const out={};for(let i=2;i<process.argv.length;i+=2){const k=process.argv[i];if(!k.startsWith('--')||!process.argv[i+1])throw Error('Expected --key value');out[k.slice(2)]=process.argv[i+1];}return out;}
export function dependencies(project){return createRequire(path.join(project,'package.json'))('@playwright/test');}
export function launchOptions(){const candidates=process.platform==='darwin'?['/Applications/Google Chrome.app/Contents/MacOS/Google Chrome']:process.platform==='win32'?[`${process.env.PROGRAMFILES}/Google/Chrome/Application/chrome.exe`,`${process.env['PROGRAMFILES(X86)']}/Microsoft/Edge/Application/msedge.exe`]:['/usr/bin/google-chrome','/usr/bin/chromium','/usr/bin/chromium-browser'];const executablePath=process.env.CHROME_PATH||candidates.find(f=>fs.existsSync(f));return{headless:true,...(executablePath?{executablePath}:{}),args:['--use-angle='+(process.env.ANGLE|| (process.platform==='darwin'?'metal':'default')),'--enable-webgl','--ignore-gpu-blocklist']};}
export function run(cmd,argv,cwd,env={}){return new Promise((resolve,reject)=>{const p=spawn(cmd,argv,{cwd,env:{...process.env,...env},stdio:'inherit',shell:process.platform==='win32'&&cmd.endsWith('.cmd')});p.on('error',reject);p.on('exit',code=>code===0?resolve():reject(Error(`${cmd} exited ${code}`)));});}
export async function server(project,port,preview=false){const child=spawn(process.execPath,[path.join(project,'node_modules/vite/bin/vite.js'),...(preview?['preview']:[]),'--host','127.0.0.1','--port',String(port),'--strictPort'],{cwd:project,stdio:['ignore','pipe','pipe']});let logs='',spawnError;child.stdout.on('data',b=>logs+=b);child.stderr.on('data',b=>logs+=b);child.on('error',e=>spawnError=e);const url=`http://127.0.0.1:${port}`;for(let i=0;i<150;i++){await new Promise(r=>setTimeout(r,100));if(spawnError||child.exitCode!==null)throw Error(`Server failed; existing ports are never killed: ${spawnError||logs}`);try{const r=await fetch(url);if(r.ok){await new Promise(r=>setTimeout(r,150));if(child.exitCode!==null)throw Error(logs);return{child,url};}}catch{} }child.kill();throw Error('Server timeout '+logs);}
export function freshReport(out){if(fs.existsSync(out)&&fs.readdirSync(out).length)throw Error('Report path must be empty: '+out);fs.mkdirSync(out,{recursive:true});}
