import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs';
const out='artifacts/controls';fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({"headless": true, "args": ["--use-angle=metal"], "channel": "chrome"});const page=await b.newPage({viewport:{width:1600,height:1000},deviceScaleFactor:1});page.setDefaultTimeout(30000);let errors=[],bad=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)bad.push(r.url())});
const check=(name,value)=>{assert.ok(value,name);checks.push(name);console.log('PASS',name)};
const read=()=>page.evaluate(()=>{let a=__RIFT.app,p=a.match.player;return{x:p.x,z:p.z,time:a.match.time,casts:p.casts,cd:p.cd,flash:p.flash,heal:p.heal,recall:p.recall,mode:a.controlMode,paused:a.match.paused,move:p.move,target:p.target,shop:a.shop,score:a.scoreboard,zoom:a.zoom}});
const clickHit=async(id,data,button='left')=>{await page.waitForFunction(({id,data})=>__RIFT.app.ui.hits.some(h=>h.id===id&&(data===undefined||h.data===data)),{id,data});const p=await page.evaluate(({id,data})=>{let a=__RIFT.app,h=a.ui.hits.find(h=>h.id===id&&(data===undefined||h.data===data));return{x:(h.x+h.w/2)/a.ui.w*innerWidth,y:(h.y+h.h/2)/a.ui.h*innerHeight}},{id,data});await page.mouse.click(p.x,p.y,{button});await page.waitForTimeout(100)};
const elapsed=async(n)=>{let s=await read();await page.waitForFunction(({time,n})=>__RIFT.app.match.time-time>=n,{time:s.time,n},{timeout:10000})};
const worldPoint=async(x,z,h=0)=>page.evaluate(({x,z,h})=>{let a=__RIFT.app,q=a.project({x,z},h);return{x:q.x/a.ui.w*innerWidth,y:q.y/a.ui.h*innerHeight}},{x,z,h});
const clickWorld=async(x,z,button='left',h=0)=>{let q=await worldPoint(x,z,h);await page.mouse.click(q.x,q.y,{button})};
const fixture=async(enemy=false)=>{await page.evaluate(enemy=>{let a=__RIFT.app,m=a.match,p=m.player;a.controls.release();m.paused=false;a.shop=false;a.scoreboard=false;a.controls.pendingSkill=null;m.stop();p.x=7200;p.z=7800;p.alive=true;p.hp=p.maxHp=20000;p.level=6;p.mp=p.maxMp=2000;p.cd=[0,0,0,0];p.buffs={};p.stun=0;p.slow=0;p.atk=100;p.autos=4;p.flash=0;p.heal=0;p.recall=0;m.projectiles=[];m.zones=[];a.focus={x:p.x,z:p.z};a.lockCamera=true;for(let e of m.entities.filter(e=>e.kind==='hero'&&!e.player))e.stun=999;let t=m.entities.find(e=>e.kind==='hero'&&e.team===1);t.x=enemy?7440:13000;t.z=enemy?7700:2000;t.hp=t.maxHp=10000;t.alive=true;t.stun=999;},enemy);await page.waitForTimeout(180)};
try{
 await page.goto('http://127.0.0.1:60068');await page.waitForFunction(()=>window.__RIFT);
 await clickHit('select',0);await clickHit('mode-practice');await clickHit('start');await page.waitForFunction(()=>__RIFT.app.screen==='game');
 check('Default control scheme is WASD, not colliding QWER', (await read()).mode==='wasd');
 // First validate the actual spawn; no fixture before this movement.
 let spawn=await read();await page.keyboard.down('KeyW');await elapsed(.6);await page.keyboard.up('KeyW');let moved=await read();check('W really moves the hero from the actual spawn',moved.z<spawn.z-120&&Math.abs(moved.x-spawn.x)<1);
 for(let [key,axis,sign] of [['KeyW','z',-1],['KeyS','z',1],['KeyA','x',-1],['KeyD','x',1],['ArrowUp','z',-1],['ArrowDown','z',1],['ArrowLeft','x',-1],['ArrowRight','x',1]]){
  await fixture();let from=await read();await page.keyboard.down(key);await elapsed(.6);await page.keyboard.up(key);let to=await read();check(`${key} moves correct direction`,(to[axis]-from[axis])*sign>120);check(`${key} does not cast skills or flash`,to.casts===from.casts&&to.flash===0);await elapsed(.2);let stopped=await read();check(`${key} stops immediately on keyup`,Math.hypot(stopped.x-to.x,stopped.z-to.z)<.01);
 }
 await fixture();let start=await read();await page.keyboard.down('KeyW');await page.keyboard.down('KeyD');await elapsed(.8);await page.keyboard.up('KeyW');await page.keyboard.up('KeyD');let diagonal=await read();let speed=Math.hypot(diagonal.x-start.x,diagonal.z-start.z)/(diagonal.time-start.time);check('Diagonal movement is normalized (not sqrt(2) faster)',speed>300&&speed<370);
 await fixture();await page.keyboard.down('KeyW');await page.keyboard.down('KeyS');let opposed=await read();await elapsed(.3);let op2=await read();check('Opposite keys cancel movement',Math.abs(op2.z-opposed.z)<1);await page.keyboard.up('KeyW');await page.keyboard.up('KeyS');
 for(let button of ['left','right']){await fixture();await clickWorld(7700,7300,button);let from=await read();await elapsed(.6);let to=await read();check(`${button} ground click moves hero`,to.x>from.x+90&&to.z<from.z-90)}
 await fixture();let from=await read(),q=await worldPoint(7800,7800);await page.mouse.move(q.x,q.y);await page.mouse.down({button:'right'});await elapsed(.2);q=await worldPoint(7200,6800);await page.mouse.move(q.x,q.y,{steps:4});await elapsed(.2);await page.mouse.up({button:'right'});check('Held right mouse retargets movement',await page.evaluate(()=>__RIFT.app.match.player.move.z<7100));
 await page.keyboard.press('KeyX');let stop=await read();await elapsed(.2);check('X stops click-to-move path',Math.hypot((await read()).x-stop.x,(await read()).z-stop.z)<1);
 for(let button of ['left','right']){await fixture(true);await page.evaluate(()=>__RIFT.app.match.player.atk=0);await clickWorld(7440,7700,button,1.5);await elapsed(.5);check(`${button} enemy click sets attack target and deals damage`,await page.evaluate(()=>{let m=__RIFT.app.match,t=m.entities.find(e=>e.kind==='hero'&&e.team===1);return m.player.target===t.id&&t.hp<10000}))}
 // Verify every keyboard spell branch and every native skill button for all heroes.
 for(let hero=0;hero<5;hero++){
  await page.evaluate(hero=>{__RIFT.app.selected=hero;__RIFT.app.start()},hero);await page.waitForTimeout(180);
  for(let i=0;i<4;i++){
   await fixture(true);let q=await worldPoint(7440,7700);await page.mouse.move(q.x,q.y);let before=await read();await page.keyboard.press(`Digit${i+1}`);await page.waitForTimeout(80);check(`Hero ${hero} skill ${i+1} keyboard activates`,(await read()).casts===before.casts+1);
   await fixture(true);q=await worldPoint(7440,7700);await page.mouse.move(q.x,q.y);before=await read();await clickHit('skill',i);if(await page.evaluate(()=>__RIFT.app.controls.pendingSkill!==null)){await clickWorld(7440,7700)}await page.waitForTimeout(80);check(`Hero ${hero} skill ${i+1} canvas button activates`,(await read()).casts===before.casts+1);
  }
 }
 await page.evaluate(()=>{__RIFT.app.selected=0;__RIFT.app.start()});await fixture(true);await page.keyboard.press('KeyC');check('C switches to classic bindings',(await read()).mode==='classic');
 for(let [i,key] of ['KeyQ','KeyW','KeyE','KeyR'].entries()){await fixture(true);let q=await worldPoint(7440,7700);await page.mouse.move(q.x,q.y);let prev=await read();await page.keyboard.press(key);await page.waitForTimeout(80);check(`Classic ${key} activates skill without movement`,(await read()).casts===prev.casts+1&&(await read()).x===prev.x)}
 await fixture();let prev=await read();await page.keyboard.down('ArrowRight');await elapsed(.4);await page.keyboard.up('ArrowRight');check('Classic arrows still move hero',(await read()).x>prev.x+90);await clickHit('controls');check('Native scheme button returns to WASD',(await read()).mode==='wasd');
 for(let method of ['keyboard','button']){await fixture();let aim=await worldPoint(7700,7600);await page.mouse.move(aim.x,aim.y);let p=await read();if(method==='keyboard')await page.keyboard.press('KeyF');else{await clickHit('summoner',0);await clickWorld(7700,7600)}let r=await read();check(`${method} flash moves by 400 and starts cooldown`,Math.abs(Math.hypot(r.x-p.x,r.z-p.z)-400)<1&&r.flash>290);await page.evaluate(()=>__RIFT.app.match.player.hp-=2000);if(method==='keyboard')await page.keyboard.press('KeyG');else await clickHit('summoner',1);check(`${method} heal starts cooldown`,(await read()).heal>230)}
 await fixture();await clickHit('recall');check('Recall canvas button starts channel',(await read()).recall>7);await page.keyboard.down('KeyA');await elapsed(.15);await page.keyboard.up('KeyA');check('Movement cancels recall',(await read()).recall===0);await page.keyboard.press('KeyB');check('B starts channel',(await read()).recall>7);await clickWorld(7500,7600);check('Mouse movement cancels recall',(await read()).recall===0);
 // Shop in the actual fountain. UI clicks must never leak as world commands.
 await page.evaluate(()=>__RIFT.app.start());await clickHit('shop');let gold=await page.evaluate(()=>__RIFT.app.match.player.gold);await clickHit('buy','sword','right');check('Right-click on item does not accidentally purchase',await page.evaluate(()=>!__RIFT.app.match.player.inventory.length));await clickHit('buy','sword');check('Left-click item buys and equips',await page.evaluate(()=>__RIFT.app.match.player.inventory.includes('sword')));let p=await read();await page.keyboard.down('KeyW');await elapsed(.3);await page.keyboard.up('KeyW');let r=await read();check('Shop blocks keyboard movement',p.x===r.x&&p.z===r.z);await clickHit('close-shop');check('Close-shop button works',!(await read()).shop);await page.keyboard.press('KeyP');check('P opens shop',(await read()).shop);await page.keyboard.press('Escape');await page.waitForFunction(()=>__RIFT.app.ui.hits.some(h=>h.id==='minimap'));check('Esc closes shop without pausing',!(await read()).shop&&!(await read()).paused);
 await fixture();await page.keyboard.down('KeyW');await elapsed(.2);await page.keyboard.press('Escape');let paused=await read();await page.keyboard.up('KeyW');await page.waitForTimeout(350);check('Esc pause freezes position/time',(await read()).time===paused.time);await clickHit('resume');await elapsed(.2);check('Resume does not retain held movement',Math.abs((await read()).z-paused.z)<1);
 await page.keyboard.down('KeyD');await elapsed(.2);await page.evaluate(()=>window.dispatchEvent(new Event('blur')));let blurred=await read();await page.keyboard.up('KeyD');await clickHit('resume');await elapsed(.2);check('Blur releases keyboard and resumes without stuck movement',Math.abs((await read()).x-blurred.x)<1);
 await clickHit('pause');check('Pause canvas button works',(await read()).paused);await page.keyboard.press('KeyP');check('P cannot open hidden shop while paused',!(await read()).shop);await clickHit('resume');
 await fixture();await page.keyboard.down('Tab');check('TAB opens scoreboard',(await read()).score);await page.keyboard.up('Tab');check('TAB release closes scoreboard',!(await read()).score);await clickHit('score');check('Score header button opens scoreboard',(await read()).score);await clickHit('score');check('Score header button closes scoreboard',!(await read()).score);
 await fixture();await clickHit('minimap');check('Minimap left click unlocks camera',await page.evaluate(()=>!__RIFT.app.lockCamera));await clickHit('minimap',undefined,'right');check('Minimap right click sets world route',await page.evaluate(()=>!!__RIFT.app.match.player.move));await page.keyboard.press('Space');check('Space returns follow camera',await page.evaluate(()=>__RIFT.app.lockCamera));await page.keyboard.press('KeyY');check('Y toggles follow camera',await page.evaluate(()=>!__RIFT.app.lockCamera));
 await page.keyboard.press('Space');let zoom=(await read()).zoom;await page.mouse.move(800,350);await page.mouse.wheel(0,160);await page.waitForTimeout(150);check('Wheel zoom works',(await read()).zoom>zoom);
 let pos=await read();await page.mouse.down({button:'middle'});await page.mouse.move(940,370,{steps:5});await page.mouse.up({button:'middle'});check('Middle drag pans camera without steering player',await page.evaluate(()=>!__RIFT.app.lockCamera));
 await page.keyboard.press('KeyX');await clickHit('pause');await clickHit('restart');check('Restart returns to fresh match',await page.evaluate(()=>__RIFT.app.match.player.inventory.length===0&&__RIFT.app.match.time<2));await clickHit('pause');await clickHit('menu');check('Menu button returns to hero select',await page.evaluate(()=>__RIFT.app.screen==='menu'));await page.keyboard.press('Enter');check('Enter starts again',await page.evaluate(()=>__RIFT.app.screen==='game'));
 await page.screenshot({path:`${out}/fixed-game.png`});check('No normal-run page or HTTP errors',errors.length===0&&bad.length===0);
 fs.writeFileSync(`${out}/browser-report.json`,JSON.stringify({checks,errors,bad,browser:await b.version(),viewport:'1600x1000',notes:'Real keyboard/mouse for all actions. Initial W test starts at actual spawn. Remaining tests use explicit position/health/cooldown fixtures for isolation; do not assert LoL fidelity.'},null,2));
}finally{await b.close();console.log({passed:checks.length,errors,bad})}
