import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import net from 'node:net';
export const SKILL=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
export const BASE=path.join(SKILL,'assets/project');
export function args(argv=process.argv.slice(2)){const r={};for(let i=0;i<argv.length;i++){const k=argv[i];if(!k.startsWith('--'))throw Error(`Unexpected argument ${k}`);if(k==='--help'){r.help=true;continue;}if(!argv[i+1]||argv[i+1].startsWith('--'))throw Error(`Missing value for ${k}`);r[k.slice(2)]=argv[++i];}return r;}
export function projectPath(value){if(!value)throw Error('--project is required');const p=fs.realpathSync(path.resolve(value));if(p===SKILL||p.startsWith(SKILL+path.sep))throw Error('Do not run against read-only skill assets; restore to a new directory first');if(!fs.existsSync(path.join(p,'package.json')))throw Error('Project package.json missing');return p;}
export async function freshDir(value){if(!value)throw Error('--out is required');const p=path.resolve(value);if(fs.existsSync(p))throw Error(`Output must not exist: ${p}`);const inputRoot=path.resolve(SKILL,'../..');if(p===SKILL||p.startsWith(SKILL+path.sep)||(path.basename(inputRoot)==='CSGame-note'&&(p===inputRoot||p.startsWith(inputRoot+path.sep))))throw Error('Reports must be outside the reference package');await fsp.mkdir(path.dirname(p),{recursive:true});await fsp.mkdir(p);return p;}
export function deps(project){const require=createRequire(path.join(project,'package.json'));let pw;try{pw=require('playwright');}catch{throw Error('Run npm ci in the output project first; Playwright is missing');}return{require,chromium:pw.chromium};}
export function chromePath(chromium,requested){const candidates=[requested,process.env.CHROME_PATH];if(process.platform==='darwin')candidates.push('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome','/Applications/Chromium.app/Contents/MacOS/Chromium');if(process.platform==='win32')for(const base of [process.env.PROGRAMFILES,process.env['PROGRAMFILES(X86)'],process.env.LOCALAPPDATA])if(base)candidates.push(path.join(base,'Google/Chrome/Application/chrome.exe'));else{};if(process.platform==='linux')candidates.push('/usr/bin/google-chrome','/usr/bin/google-chrome-stable','/usr/bin/chromium','/usr/bin/chromium-browser','/snap/bin/chromium');candidates.push(chromium.executablePath());if(requested||process.env.CHROME_PATH){const explicit=requested||process.env.CHROME_PATH;if(!fs.existsSync(explicit))throw Error(`Chrome does not exist: ${explicit}`);return explicit;}for(const c of candidates)if(c&&fs.existsSync(c))return c;throw Error('No Chrome/Chromium found. Set CHROME_PATH or explicitly run npx playwright install chromium in the output project.');}
export const browserArgs=()=>process.env.ANGLE? [`--use-angle=${process.env.ANGLE}`]:process.platform==='darwin'?['--use-angle=metal']:[];
export const sleep=ms=>new Promise(r=>setTimeout(r,ms));
export async function freePort(){const server=net.createServer();await new Promise((ok,bad)=>{server.once('error',bad);server.listen(0,'127.0.0.1',ok);});const port=server.address().port;await new Promise(r=>server.close(r));return port;}
export async function run(command,parameters,{cwd,log,env={},timeout=180000}={}){const stream=log?fs.createWriteStream(log):null;const proc=spawn(command,parameters,{cwd,env:{...process.env,...env},stdio:['ignore','pipe','pipe']});let text='',timedOut=false;for(const output of [proc.stdout,proc.stderr])output.on('data',b=>{stream?.write(b);text+=b.toString();if(text.length>200000)text=text.slice(-200000);});let killer;const timer=setTimeout(()=>{timedOut=true;proc.kill('SIGTERM');killer=setTimeout(()=>proc.kill('SIGKILL'),2500);},timeout);const result=await new Promise(resolve=>{proc.once('error',e=>resolve({code:1,error:e.message}));proc.once('close',(code,signal)=>resolve({code:code??1,signal}));});clearTimeout(timer);clearTimeout(killer);if(stream)await new Promise(r=>stream.end(r));return{...result,timedOut,text};}
export async function startServer(project,mode,log){const port=await freePort(),vite=path.join(project,'node_modules/vite/bin/vite.js');if(!fs.existsSync(vite))throw Error('Vite is missing. Run npm ci first.');const parameters=[vite,...(mode==='production'?['preview']:[]),'--host','127.0.0.1','--port',String(port),'--strictPort'];const stream=fs.createWriteStream(log);const proc=spawn(process.execPath,parameters,{cwd:project,stdio:['ignore','pipe','pipe']});proc.stdout.pipe(stream,{end:false});proc.stderr.pipe(stream,{end:false});let startupError;proc.on('error',e=>{startupError=e;});const url=`http://127.0.0.1:${port}`;const stop=async()=>{if(proc.exitCode===null&&proc.signalCode===null){proc.kill('SIGTERM');for(let i=0;i<25&&proc.exitCode===null&&proc.signalCode===null;i++)await sleep(100);if(proc.exitCode===null&&proc.signalCode===null)proc.kill('SIGKILL');}await new Promise(r=>stream.end(r));};for(let i=0;i<150;i++){if(startupError||proc.exitCode!==null){await stop();throw Error(`Vite startup failed: ${startupError?.message||proc.exitCode}`);}try{const r=await fetch(url,{signal:AbortSignal.timeout(500)});if(r.ok)return{url,port,stop};}catch{}await sleep(100);}await stop();throw Error('Timed out waiting for Vite');}
